from enum import IntEnum


class OperationError(IntEnum):
    NONE = 0
    HLC_HEARTBEAT_LOST = 1
    OPERATION_NOT_ENABLED = 2
    INVALID_ARC = 3
    TOOL_INDEX_OUT_OF_RANGE = 4
    JOINT_LIMIT_EXCEEDED = 5
    KINEMATICS_FK_INVALID_VALUE = 6
    KINEMATICS_IK_INVALID_VALUE = 7
    KINEMATICS_INVALID_KIN_CHAIN_PARAMS = 8
    JOINT_DISCONTINUITY = 9
    JOINT_OVER_SPEED = 10
    INVALID_ROTATION = 11
    CONFIG_RELOADED = 12
    KINEMATICS_ENVELOPE_VIOLATION = 13
    KINEMATICS_NEAR_SINGULARITY = 14
